global:
  scrape_interval: 60s
  scrape_timeout: 10s
  evaluation_interval: 10s


scrape_configs:

  - job_name: 'prometheus-sentry-exporter'
    static_configs:
      - targets:
        - 'prometheusexporter:9102'

